# CI for PuzzleBox.NeuralNets
# Build & Test

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# .Net Core 2.2 SDK
- task: UseDotNet@2
  displayName: 'Use dotnet sdk 2.2.x'
  inputs:
    packageType: sdk
    version: 2.2.x
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet
    
# Build
- script: dotnet build -c $(buildConfiguration)
  displayName: 'Build'

# Test
- script: dotnet test -c $(buildConfiguration) --no-build
  displayName: 'Test'
